name: Build C++ App with MSVC

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Qt
        uses: miurahr/setup-qt@v3
        with:
          version: '6.5.3'  # 例: 必要なQt6のバージョンを指定

      - name: Download and install WiX Toolset 3.11.2
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile wix.zip
          Expand-Archive wix.zip -DestinationPath wix
          echo "$PWD/wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up MSVC environment and build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build
          cmake --build build --config Debug

      - name: Build MSI installer
        run: cmake --build build --target package

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_program_msvc
          path: ./build/Debug/Calculator.exe

      - uses: actions/upload-artifact@v4
        with:
          name: CalculatorInstaller
          path: build/*.msi